import {createReadState,READ_STORAGE_KEY} from './read-state.mjs';
import {categories,designs,kstDate,matches,todayPicks,sorted,escapeHTML as esc,safeURL} from './core.mjs';
const $=s=>document.querySelector(s);
const readState=createReadState(()=>window.localStorage);
let papers=[],dataset=null,liveData=null,limit=20,category='all';
const filters=()=>({category,search:$('#search').value,journal:$('#journal').value,design:$('#design').value,species:[...document.querySelectorAll('[name=species]:checked')].map(x=>x.value),evidence:[...document.querySelectorAll('[name=evidence]:checked')].map(x=>x.value)});
const labels={soft_tissue_surgery:'Soft tissue',orthopedics:'Orthopedics',gastroenterology:'Gastroenterology',infectious_disease:'Infectious disease',nephrology:'Nephrology',cardiology:'Cardiology'};
function dateLabel(p){const d=p.online_publication_date||p.publication_date;return d?d.replaceAll('-','.'):(p.publication_date_raw||'발행일 미보고');}
function link(url,label){const u=safeURL(url);return u?`<a href="${u}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`:'';}
function details(p){return `<div class="details" hidden id="detail-${esc(p.id)}"><p class="evidence-scope">${p.evidence_source==='full_text'?'확보한 전문에 근거한 상세 요약':'초록에 근거한 상세 요약 · 전문은 검토하지 않았습니다.'}</p><h4>연구 목적 <small>Objective</small></h4><p>${esc(p.objective||'Not reported in this summary.')}</p><h4>연구 대상과 방법 <small>Study methods</small></h4><p>${esc(p.study_methods||'현재 요약에는 연구 방법이 정리되어 있지 않습니다. 출처에서 확인해 주세요.')}</p><h4>주요 결과 <small>What they found · 논문에서 보고한 내용</small></h4>${p.key_results.map((k,index)=>`<div class="finding"><p><span class="finding-number">${index+1}.</span> ${esc(k.result)}</p><details class="source-quote"><summary>출처 근거 확인</summary><blockquote lang="en">${esc(k.evidence_quote)}</blockquote></details></div>`).join('')||'<p>Not reported.</p>'}<h4>저자의 결론 <small>Authors’ conclusion</small></h4><p>${esc(p.authors_conclusion||'Not reported in this summary.')}</p><h4>연구의 한계와 해석 범위 <small>Limitations</small></h4><ul>${p.limitations.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${p.recommended?`<h4>Why recommended</h4><p>${esc(p.recommendation_reason)}</p>`:''}<h4>Evidence & provenance</h4>${p.evidence_note?`<p>${esc(p.evidence_note)}</p>`:""}<p>${p.evidence_source==='full_text'?'Full-text reviewed — 실제 확보한 전문 기반':'Abstract-based summary — 초록 기반'} · ${esc(p.summary_generated_at?.slice(0,10)||'')}<br>${dataset.mode==='reference'?'초기 검증용 참고 요약 · 자동 OpenAI 분석 결과가 아닙니다.':`분석 모델: ${esc(p.analysis_model||'not reported')}`}</p>${link(p.evidence_url,'분석에 사용한 출처')}</div>`;}
function card(p){const read=readState.isRead(p);const tags=[p.primary_category,...p.tags.filter(x=>x!==p.primary_category)];return `<article class="paper${read?' is-read':''}" id="paper-${esc(p.id)}"><div class="paper-meta"><span class="journal-name">${esc(p.journal)}<span class="date">· ${esc(dateLabel(p))}</span></span><span class="evidence-badge ${p.evidence_source==='full_text'?'full':''}">${p.evidence_source==='full_text'?'Full-text reviewed':'Abstract-based summary'}</span></div><div class="title-row"><h3 lang="en">${esc(p.title)}</h3>${p.recommended?`<button class="star-button" data-action="why" data-id="${esc(p.id)}" title="Why recommended: ${esc(p.recommendation_reason)}" aria-label="Why recommended" aria-expanded="false" aria-controls="why-${esc(p.id)}">☆</button>`:''}</div>${p.recommended?`<div class="why" hidden id="why-${esc(p.id)}"><strong>WHY RECOMMENDED</strong>${esc(p.recommendation_reason)}</div>`:''}<div class="paper-tags">${tags.map(t=>`<span class="tag ${esc(t)}">${esc(categories[t]||labels[t]||t.replaceAll('_',' '))}</span>`).join('')}</div><p class="study-meta">${esc(designs[p.study_design]||'Other')} <span aria-hidden="true">·</span> ${p.species.map(s=>s==='dog'?'Dog':'Cat').join(' & ')} <span aria-hidden="true">·</span> n = ${p.sample_size??'not reported'}</p><section class="research-summary" aria-label="연구 요약"><h4>연구 요약 <span>논문에서 보고한 내용</span></h4><p class="one-line">${esc(p.one_sentence_summary)}</p></section><button class="takeaway-toggle" data-action="takeaway" data-id="${esc(p.id)}" aria-expanded="false" aria-controls="takeaway-${esc(p.id)}">AI 임상 해석 보기 ＋</button><div class="takeaway" hidden id="takeaway-${esc(p.id)}"><h4>CLINICAL TAKEAWAY</h4><p class="ai-interpretation-label">AI가 자의적으로 해석한 내용이며, 논문 저자의 결론이 아닙니다.</p><p>${esc(p.clinical_takeaway)}</p></div>${details(p)}<div class="paper-bottom"><div class="paper-actions"><button class="read-button" data-action="read" data-id="${esc(p.id)}" aria-pressed="${read}" title="이 브라우저에 저장됩니다. 다시 누르면 읽음 표시를 취소합니다.">${read?'✓ 읽음':'읽음 표시'}</button><button class="more-button" data-action="more" data-id="${esc(p.id)}" aria-expanded="false" aria-controls="detail-${esc(p.id)}">연구 방법·결과·한계 자세히 보기 ＋</button></div><div class="paper-links">${link(p.pubmed_url,'PubMed')}${link(p.doi?'https://doi.org/'+p.doi:null,'DOI')}${link(p.publisher_url,'Publisher')}</div></div></article>`;}
function renderPicks(){const section=$('#picks-section');section.hidden=category!=='all';if(section.hidden)return;const list=todayPicks(papers).filter(p=>matches(p,filters()));$('#picks-caption').textContent=dataset.mode==='reference'?'초기 검증 샘플에서 선정':'오늘 발견한 추천 논문';$('#picks-content').innerHTML=list.length?list.map((p,i)=>`<article class="pick"><div class="pick-top"><span>${esc(categories[p.primary_category])}</span><span class="pick-index">0${i+1}</span></div><h3 lang="en">${esc(p.title)}</h3><p class="pick-result">${esc(p.one_sentence_summary)}</p><p class="pick-reason">${esc(p.recommendation_reason)}</p><button data-action="jump" data-id="${esc(p.id)}">Clinical takeaway 읽기 ↗</button></article>`).join(''):'<p class="empty-inline">No major clinical papers selected today.<br>오늘 새로 발견한 추천 논문 중 현재 필터에 맞는 논문이 없습니다.</p>';}
function render(){const list=sorted(papers.filter(p=>matches(p,filters())));$('#list-title').textContent=category==='all'?'Latest papers':category==='recommended'?'Recommended papers':categories[category];$('#result-count').textContent=`${list.length} papers`;$('#paper-list').innerHTML=list.slice(0,limit).map(card).join('')||`<div class="empty"><h3>${papers.length?'조건에 맞는 논문이 없습니다.':'아직 분석된 논문이 없습니다.'}</h3><p>${papers.length?'검색어나 필터를 조정해 보세요.':'첫 자동 수집과 AI 분석이 완료되면 이곳에 논문이 표시됩니다.'}</p>${papers.length?'<button data-action="reset">필터 초기화</button>':'<button data-action="reference">실제 논문 검증 샘플 보기</button>'}</div>`;$('#paper-list').setAttribute('aria-busy','false');$('#load-more').hidden=limit>=list.length;renderPicks();}
function reset(){category='all';$('#search').value='';$('#filters-form').reset();document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('active',b.dataset.category==='all');b.setAttribute('aria-pressed',String(b.dataset.category==='all'));});limit=20;render();}
function setDataset(data){dataset=data;papers=data.papers;const journalMap=new Map(papers.map(p=>[p.journal_id,p.journal]));$('#journal').innerHTML='<option value="">모든 저널</option>'+[...journalMap.entries()].sort((a,b)=>a[1].localeCompare(b[1])).map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');$('#count-all').textContent=papers.length;const notice=$('#notice');if(data.mode==='reference'){notice.hidden=false;notice.innerHTML='초기 검증 샘플 · 실제 논문의 초록 또는 확보한 전문으로 작성한 참고 요약입니다. 자동 AI 업데이트는 아직 연결되지 않았습니다. <button data-action="live">실제 수집 화면 보기</button>';$('#updated').textContent='자동 분석 연결 대기';}else{const stamp=data.last_successful_collection;$('#updated').textContent=stamp?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(stamp)):'첫 수집 대기';const stale=stamp&&Date.now()-new Date(stamp).getTime()>48*3600000;notice.hidden=!stale&&!['partial','failed','setup_required','not_started'].includes(data.health?.status);notice.textContent=stale?'최근 수집이 48시간 이상 지났습니다. 자동 업데이트 실행 상태를 확인하세요.':data.health?.status==='partial'?'일부 수집 또는 분석이 실패했습니다. 기존 논문은 보존되며 다음 실행에서 재시도합니다.':'자동 수집·분석 연결이 필요합니다. 현재 완료된 논문만 표시합니다.';}reset();}
async function loadJSON(name){const response=await fetch(`./data/${name}`,{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const value=await response.json();if(!Array.isArray(value.papers))throw new Error('Invalid paper data');return value;}
async function reference(){setDataset(await loadJSON('reference-papers.json'));}
document.addEventListener('click',async event=>{const btn=event.target.closest('button');if(!btn)return;if(btn.dataset.category){category=btn.dataset.category;limit=20;document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('active',b===btn);b.setAttribute('aria-pressed',String(b===btn));});render();return;}const id=btn.dataset.id;switch(btn.dataset.action){case 'read':{
  const paper=papers.find(p=>p.id===id);
  if(!paper)break;
  const result=readState.toggle(paper);
  syncReadMarkers();
  $('#reading-status').textContent=result.persisted?'': '브라우저 저장소를 사용할 수 없어 읽음 표시는 현재 화면에서만 유지됩니다.';
  break;
}case 'takeaway':{toggleTakeaway(id,btn);break;}case 'more':{const panel=document.getElementById('detail-'+id);panel.hidden=!panel.hidden;btn.setAttribute('aria-expanded',String(!panel.hidden));btn.textContent=panel.hidden?'연구 방법·결과·한계 자세히 보기 ＋':'상세 요약 접기 −';break;}case 'why':{const panel=document.getElementById('why-'+id);panel.hidden=!panel.hidden;btn.setAttribute('aria-expanded',String(!panel.hidden));break;}case 'jump':{limit=papers.length;render();const article=document.getElementById('paper-'+id);article?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});const toggle=article?.querySelector('[data-action=takeaway]');if(toggle){toggleTakeaway(id,toggle,true);toggle.focus({preventScroll:true});}break;}case 'reset':reset();break;case 'live':setDataset(liveData);break;case 'reference':try{await reference();}catch{$('#notice').hidden=false;$('#notice').textContent='검증 샘플을 불러오지 못했습니다.';}break;case 'retry':location.reload();break;}});
$('#filter-toggle').addEventListener('click',()=>{const open=$('.filters').classList.toggle('is-open');$('#filter-toggle').setAttribute('aria-expanded',String(open));$('#filter-toggle').textContent=open?'필터 접기 −':'필터 열기 ＋';});
$('#filters-form').addEventListener('change',()=>{limit=20;render();});$('#filters-form').addEventListener('submit',e=>e.preventDefault());$('#search').addEventListener('input',()=>{limit=20;render();});$('#reset').addEventListener('click',reset);$('#load-more').addEventListener('click',()=>{limit+=20;render();});$('#today').textContent=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Seoul',day:'numeric',month:'long',year:'numeric'}).format(new Date());
try{liveData=await loadJSON('papers.json');if(liveData.papers.length)setDataset(liveData);else await reference();}catch{$('#paper-list').setAttribute('aria-busy','false');$('#paper-list').innerHTML='<div class="empty" role="alert"><h3>논문 데이터를 불러오지 못했습니다.</h3><p>네트워크 연결을 확인한 뒤 다시 시도하세요.</p><button data-action="retry">다시 시도</button></div>';$('#updated').textContent='데이터 확인 실패';$('#picks-section').hidden=true;}

function syncReadMarkers(){
  for(const paper of papers){
    const article=document.getElementById('paper-'+paper.id);
    if(!article)continue;
    const read=readState.isRead(paper);
    article.classList.toggle('is-read',read);
    const button=article.querySelector('[data-action="read"]');
    button.setAttribute('aria-pressed',String(read));
    button.textContent=read?'✓ 읽음':'읽음 표시';
  }
}
window.addEventListener('storage',event=>{
  if(event.key===READ_STORAGE_KEY||event.key===null){readState.reload();syncReadMarkers();}
});

function toggleTakeaway(id,button,open){
  const panel=document.getElementById('takeaway-'+id);
  if(!panel)return;
  panel.hidden=open===undefined?!panel.hidden:!open;
  button.setAttribute('aria-expanded',String(!panel.hidden));
  button.textContent=panel.hidden?'AI 임상 해석 보기 ＋':'AI 임상 해석 접기 −';
}
