export const categories={surgery:'Surgery',internal_medicine:'Internal Medicine',oncology:'Oncology',other:'Other'};
export const designs={randomized_controlled_trial:'Randomized controlled trial',prospective:'Prospective',retrospective:'Retrospective',systematic_review:'Systematic review / Meta-analysis',case_series:'Case series',case_report:'Case report',other:'Other'};
export function kstDate(value=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));}
export function searchable(p){return [p.title,p.journal,p.disease_or_topic,...p.tags,p.clinical_takeaway,p.one_sentence_summary,p.study_methods||'',...p.key_results.map(x=>x.result)].join(' ').normalize('NFKC').toLocaleLowerCase();}
export function matches(p,f){const terms=(f.search||'').normalize('NFKC').toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);return (!f.category||f.category==='all'||(f.category==='recommended'?p.recommended:p.primary_category===f.category||p.tags.includes(f.category)))&&(!f.species?.length||f.species.some(s=>p.species.includes(s)))&&(!f.journal||p.journal_id===f.journal)&&(!f.design||p.study_design===f.design)&&(!f.evidence?.length||f.evidence.includes(p.evidence_source))&&terms.every(t=>searchable(p).includes(t));}
export function todayPicks(papers,today=kstDate()){return papers.filter(p=>p.recommended&&p.clinical_relevance==='direct'&&kstDate(p.discovered_at)===today).sort((a,b)=>(b.online_publication_date||b.publication_date||'').localeCompare(a.online_publication_date||a.publication_date||'')).slice(0,3);}
export function sorted(papers){return [...papers].sort((a,b)=>(b.online_publication_date||b.publication_date||'').localeCompare(a.online_publication_date||a.publication_date||'')||b.discovered_at.localeCompare(a.discovered_at));}
export function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?escapeHTML(u.href):'';}catch{return '';}}
